### PR TITLE
Various tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
Marked as draft until we have the SVG logo and redo the images.

Preview: <https://trusting-pare-a516e2.netlify.com/>

### CODE REVIEW

**Comment by taniarascia** [comment]
@XhmikosR Sorry for the delay, I was out of town/AFK for the Holiday weekend. I'll bring in the SVG and review the PRs tonight. 🙂

**Comment by XhmikosR** [comment]
No worries! After we have the SVG I'll redo this PR.

**Comment by taniarascia** [comment]
SVG: https://github.com/taniarascia/new-moon/blob/master/images/new-moon.svg

**Comment by XhmikosR** [comment]
@taniarascia: I think this is ready. I didn't go with 8-bit for the new images because this can cause issues with some image editing programs, so I'd rather do it in a separate commit later (so that still have access to the original files via `git log`). That being said, we'd save another ~1.5-2.0 MB.

A few notes:

1. You should use the SVG logo (and remove the old 2 PNGs) when possible like in README.md etc. In this PR I use it for the docs.
2. The subpackages' package.json files need some love, their info seems wrong in some cases like repo URL etc. Also, if they are not supposed to be published they should be marked as `private` to be safe
3. Finally, the whole PNG optimization step you should do it when committing the new files so that we don't bloat the repo :) I'd go with lossless optimization which is perfectly safe, but you can experiment with lossy too. For the docs images, we already use 8-bit PNGs BTW. I assume you are on macOS, so you can use https://kraken.io/web-interface or https://imageoptim.com/mac if you prefer a GUI.

**Comment by taniarascia** [comment]
Sorry, not sure why notifications are intermittent for me so I took a while to get back to this. Looks great. I still need to go through and fix the subpackages package.json/README files and bring them all in.

**Pull request merged**
